# Generated by Django 4.2.3 on 2023-07-17 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebleslist_app', '0003_empresa_inmueble_created_alter_inmueble_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='empresa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='inmuebles', to='inmuebleslist_app.empresa'),
            preserve_default=False,
        ),
    ]
